<?php

/*
|--------------------------------------------------------------------------
| API Documentation — English
|--------------------------------------------------------------------------
|
| Text injected by App\Docs\OpenApiLocalizer into the OpenAPI document
| generated by Scramble for the English variant (/docs/api/en.json).
|
| Operations are keyed by their canonical "<method> <path>" key (without the
| "api/" prefix and without the leading slash), e.g. "post v3/webhook/singapur".
|
| Keep this file in sync with lang/es/api.php (the default language).
|
*/

return [

    'info' => [
        'title' => 'Nexum Core — China Integration API',
        'description' => <<<'MD'
Backend API of **Backend Bridge Incorporation** for incorporating Mexican
companies from case files submitted from China through the internal **"Singapur"**
relay.

It covers the inbound webhooks (KYC case files and denomination rulings), the
public lookup endpoints for the **MUA** portal (Secretaría de Economía), and the
authenticated endpoints used by the notary team.

### Authentication
- **`bearerAuth`** — JWT (`Authorization: Bearer <token>`) for the notary team endpoints.
- **`singapurSecret`** — shared secret (`X-Nexum-Secret`) for the China relay webhook.
- **`muaBotSignature`** — HMAC-SHA256 signature (`X-Signature`) for the MUA bot callback.
- **`muaBotApiKey`** — API key (`X-Bot-Api-Key`) for the MUA bot poll.
- **`docusignSignature`** — HMAC signature (`X-DocuSign-Signature-1`) for the DocuSign webhook.
MD,
    ],

    'tags' => [
        'Webhooks (China / Singapur)' => 'Inbound endpoints Nexum receives from the China relay and external services.',
        'MUA / Denominations' => 'Availability checks and resolution of company denominations in the Secretaría de Economía portal.',
        'Authentication' => 'Issuing and managing JWT tokens for API consumers.',
        'Registrations' => 'Reading and advancing the incorporation pipeline of case files.',
    ],

    'operations' => [

        // -- China / external webhooks ---------------------------------------
        'post v3/webhook/singapur' => [
            'tag' => 'Webhooks (China / Singapur)',
            'summary' => 'Receive case file from China (Singapur relay)',
            'description' => <<<'MD'
Primary entry point for the China relay. Receives the full KYC case file of a
company to be incorporated, with documents as **inline base64** inside the JSON
(no server-to-server download).

The endpoint validates the shared secret in the `X-Nexum-Secret` header, guarantees
**idempotency** via the `id` field (package UUID), and queues processing in the
background, responding immediately.

**Responses:** `202` accepted · `401` invalid secret · `409` event already received · `422` missing `id`.
MD,
        ],

        'post v3/webhook/docusign' => [
            'tag' => 'Webhooks (China / Singapur)',
            'summary' => 'DocuSign Connect webhook',
            'description' => <<<'MD'
Receives envelope status-change notifications from DocuSign Connect for the
partner-signature stage. Validates the **HMAC-SHA256** signature in the
`X-DocuSign-Signature-1` header and queues processing within DocuSign's 5-second
timeout requirement.

**Responses:** `202` accepted · `401` invalid or missing HMAC.
MD,
        ],

        'post v3/webhook/mua-bot' => [
            'tag' => 'Webhooks (China / Singapur)',
            'summary' => 'MUA bot callback (denomination ruling)',
            'description' => <<<'MD'
The MUA bot (Python microservice) calls this endpoint when the Secretaría de
Economía resolves a company denomination (**approved** or **rejected**).

When approved, the bot sends the **denomination authorization certificate**
("constancia") as base64; Nexum stores it in R2, creates the `Document`, and marks
the `LegalName` as approved (automatically rejecting the others in the case file).

Security: **HMAC-SHA256** signature (`X-Signature`) with replay protection
(5-minute window via `timestamp`).

**Responses:** `200` recorded · `401` invalid / expired signature · `404` denomination not found · `422` invalid status · `500` processing failure.
MD,
        ],

        // -- MUA / Denominations ---------------------------------------------
        'post v3/legal-name/check-availability' => [
            'tag' => 'MUA / Denominations',
            'summary' => 'Check denomination availability (public)',
            'description' => <<<'MD'
Checks whether a proposed company denomination is available in the MUA portal.

It is intentionally **public** (no JWT) so the China relay can query it directly
while the Chinese client is choosing company names.

**Responses:** `200` with `available: true|false` · `503` when the MUA portal is unavailable (`available: null`).
MD,
        ],

        // -- MUA bot: pending poll -------------------------------------------
        'get v3/mua-bot/pending' => [
            'tag' => 'MUA / Denominations',
            'summary' => 'Pending denominations for the MUA bot',
            'description' => <<<'MD'
Returns denominations in `PENDING` or `PROCESS` status that already have a FIEL
account assigned, along with the credentials (certificate, key and password in
base64) so the bot can authenticate against the SE portal.

Security: shared API key in the `X-Bot-Api-Key` header.

**Responses:** `200` with the list · `401` unauthorized.
MD,
        ],

        // -- Authentication ---------------------------------------------------
        'post v3/auth/login' => [
            'tag' => 'Authentication',
            'summary' => 'Log in (JWT)',
            'description' => 'Authenticates with email and password and returns a bearer JWT token together with its expiration time.',
        ],
        'get v3/auth/me' => [
            'tag' => 'Authentication',
            'summary' => 'Authenticated user profile',
            'description' => 'Returns the data of the user tied to the current JWT token, including their role.',
        ],
        'post v3/auth/logout' => [
            'tag' => 'Authentication',
            'summary' => 'Log out',
            'description' => 'Invalidates the current JWT token.',
        ],
        'post v3/auth/refresh' => [
            'tag' => 'Authentication',
            'summary' => 'Refresh token',
            'description' => 'Invalidates the current JWT token and returns a new one.',
        ],

        // -- Registrations ----------------------------------------------------
        'get v3/registrations' => [
            'tag' => 'Registrations',
            'summary' => 'List registrations',
            'description' => 'Returns a paginated list of registrations ordered from newest to oldest. Supports `?per_page=N` (max 100).',
        ],
        'get v3/registrations/{singapurClientCode}' => [
            'tag' => 'Registrations',
            'summary' => 'Get registration by client code',
            'description' => 'Returns a registration identified by its Singapur client code (e.g. `000001`) with its shareholders, denominations and documents.',
        ],
        'post v3/registrations/{singapurClientCode}/advance' => [
            'tag' => 'Registrations',
            'summary' => 'Advance registration stage',
            'description' => 'Advances the registration to the next pipeline stage, recording the transition for audit. Accepts an optional `reason` in the body.',
        ],
        'post v3/registrations/{registration}/legal-names' => [
            'tag' => 'MUA / Denominations',
            'summary' => 'Add a denomination to a registration',
            'description' => 'Adds a company denomination proposal (max 4 per registration; blocked when one is already approved).',
        ],
        'delete v3/registrations/{registration}/legal-names/{legalName}' => [
            'tag' => 'MUA / Denominations',
            'summary' => 'Remove a denomination from a registration',
            'description' => 'Removes a denomination proposal (a minimum of 3 must remain; not allowed when in process or approved).',
        ],
    ],
];
