<?php

namespace App\Filament\Resources\RegistrationResource\Actions;

use App\Enums\DocumentTypeEnum;
use App\Enums\RegistrationStageEnum;
use App\Models\Document;
use App\Models\Registration;
use App\Services\DocuSign\DocuSignService;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Illuminate\Support\HtmlString;

/**
 * Filament header action to send the acta constitutiva for electronic signature via DocuSign.
 *
 * Visible only when the registration is in the PARTNER_SIGNATURE stage and an
 * ACTA_FINAL document with an anchor_map exists (generated by GenerateActaDocxService).
 *
 * On confirmation:
 *   1. Calls DocuSignService::sendActaForSignature() to create the DocuSign envelope.
 *   2. Generates per-signer embedded signing URLs and displays them as clickable links.
 *   3. If an envelope was already created, shows the existing links without re-sending.
 *
 * The action re-uses the action modal as a result display: after the envelope is created
 * the modal body is replaced with the signer links (one per shareholder).
 */
class PartnerSignatureAction
{
    /**
     * Build and return the configured Filament Action instance.
     *
     * @param  Registration  $registration  The current registration record.
     * @param  DocuSignService  $docuSignService  Injected service for DocuSign operations.
     */
    public static function make(
        Registration $registration,
        DocuSignService $docuSignService,
    ): Action {
        $actaFinal = $registration->documents()
            ->where('type', DocumentTypeEnum::ACTA_FINAL)
            ->latest()
            ->first();

        $alreadySent = $actaFinal !== null
            && isset($actaFinal->template_data['sign_status']['envelope_id']);

        $buttonLabel = $alreadySent
            ? '✉ Links de firma'
            : '✍ Enviar a firma';

        return Action::make('partner_signature')
            ->label($buttonLabel)
            ->icon($alreadySent ? 'heroicon-o-link' : 'heroicon-o-pencil-square')
            ->color($alreadySent ? 'gray' : 'warning')
            ->visible(
                fn (): bool => $registration->stage === RegistrationStageEnum::PARTNER_SIGNATURE
                    && $actaFinal !== null
                    && ! empty($actaFinal->template_data['anchor_map'] ?? [])
            )
            ->modalHeading($alreadySent ? 'Links de firma DocuSign' : 'Enviar acta a firma electrónica')
            ->modalDescription(
                fn (): HtmlString => $alreadySent
                    ? new HtmlString(self::buildLinksHtml($registration, $actaFinal, $docuSignService))
                    : new HtmlString(
                        '<p>Se enviará el acta constitutiva a <strong>DocuSign</strong> para la firma electrónica de todos los accionistas.</p>'
                        .'<p class="mt-2 text-sm text-gray-500">Esta acción crea el envelope y genera los links de firma. Cada accionista recibirá un correo de DocuSign con su enlace.</p>'
                    )
            )
            ->modalSubmitActionLabel($alreadySent ? 'Cerrar' : 'Enviar a DocuSign ✓')
            ->modalCancelActionLabel($alreadySent ? null : 'Cancelar')
            ->action(function () use ($registration, $actaFinal, $alreadySent, $docuSignService): void {
                // If already sent, the modal acts as a read-only viewer — no action needed.
                if ($alreadySent) {
                    return;
                }

                try {
                    $envelopeId = $docuSignService->sendActaForSignature($registration);

                    // Refresh the record so the updated template_data is available for link generation.
                    $actaFinal->refresh();

                    $linksHtml = self::buildLinksHtml($registration, $actaFinal, $docuSignService);

                    Notification::make()
                        ->title('Acta enviada a firma')
                        ->body(new HtmlString("Envelope ID: <code>{$envelopeId}</code><br>Links generados para cada accionista."))
                        ->success()
                        ->persistent()
                        ->send();

                } catch (\Throwable $e) {
                    Notification::make()
                        ->title('Error al enviar a DocuSign')
                        ->body($e->getMessage())
                        ->danger()
                        ->persistent()
                        ->send();
                }
            });
    }

    /**
     * Build an HTML block listing each signer's embedded signing URL.
     *
     * Generates one signing URL per entry in the anchor_map. If DocuSign returns null
     * for any signer, that row shows an error message instead.
     *
     * @param  Registration  $registration  The expedient whose envelope was created.
     * @param  Document  $actaFinal  The ACTA_FINAL document holding the envelope_id and anchor_map.
     * @param  DocuSignService  $docuSignService  Service used to generate signing URLs.
     * @return string HTML string ready to embed in a Filament modal description.
     */
    private static function buildLinksHtml(
        Registration $registration,
        Document $actaFinal,
        DocuSignService $docuSignService,
    ): string {
        $envelopeId = $actaFinal->template_data['sign_status']['envelope_id'] ?? null;

        if ($envelopeId === null) {
            return '<p class="text-red-600">No se encontró el envelope_id. Intenta enviar de nuevo.</p>';
        }

        $anchorMap = $actaFinal->template_data['anchor_map'] ?? [];
        $returnUrl = config('services.docusign.return_url', config('app.url').'/admin');

        $html = "<div class='space-y-3'>";
        $recipientIndex = 1;

        foreach ($anchorMap as $key => $signerInfo) {
            $signingUrl = $docuSignService->generateSigningUrl(
                envelopeId: $envelopeId,
                recipientId: (string) $recipientIndex,
                recipientEmail: $signerInfo['email'],
                recipientName: $signerInfo['nombre'],
                returnUrl: $returnUrl,
            );

            $nombre = htmlspecialchars($signerInfo['nombre'], ENT_QUOTES);
            $email = htmlspecialchars($signerInfo['email'], ENT_QUOTES);
            $recipientIndex++;

            if ($signingUrl !== null) {
                $url = htmlspecialchars($signingUrl, ENT_QUOTES);
                $html .= "<div class='p-3 bg-gray-50 rounded-lg border'>"
                    ."<p class='font-semibold text-sm'>{$nombre}</p>"
                    ."<p class='text-xs text-gray-500 mb-2'>{$email}</p>"
                    ."<a href='{$url}' target='_blank' class='inline-flex items-center gap-1 text-sm text-primary-600 hover:underline'>"
                    .'✍ Abrir link de firma</a>'
                    .'</div>';
            } else {
                $html .= "<div class='p-3 bg-red-50 rounded-lg border border-red-200'>"
                    ."<p class='font-semibold text-sm'>{$nombre}</p>"
                    ."<p class='text-xs text-red-600'>No se pudo generar el link de firma. Verifica el estado del envelope en DocuSign.</p>"
                    .'</div>';
            }
        }

        $html .= '</div>';

        return $html;
    }
}
