<?php

namespace App\Enums;

/**
 * Document types attached to a registration expedient.
 *
 * KYC documents (prefix KYC_) arrive from China via the Singapur relay webhook
 * in the initial package. All other types are generated internally by Nexum
 * during the incorporation process.
 */
enum DocumentTypeEnum: string
{
    // -------------------------------------------------------------------------
    // KYC documents — sent by China in the initial webhook package (DATA_RECEIVED).
    // Field names mirror the relay JSON: naturalTaxCertificate, naturalProofAddress,
    // naturalMarriageCertificate, naturalSpousePassport.
    // -------------------------------------------------------------------------

    /** Chinese Tax ID / National ID card (证). One per shareholder. */
    case KYC_TAX_CERTIFICATE = 'kyc_tax_certificate';

    /** Chinese proof of address (水电费单 or similar). One per shareholder. */
    case KYC_PROOF_OF_ADDRESS = 'kyc_proof_of_address';

    /** Chinese marriage certificate (结婚证). Only for married shareholders. */
    case KYC_MARRIAGE_CERTIFICATE = 'kyc_marriage_certificate';

    /** Spouse's passport. Only for married shareholders. */
    case KYC_SPOUSE_PASSPORT = 'kyc_spouse_passport';

    // -------------------------------------------------------------------------
    // Documents generated internally during the incorporation pipeline.
    // -------------------------------------------------------------------------

    /** Shareholder's own passport (may be uploaded manually by the notary team). */
    case PASSPORT = 'passport';

    /** Visa document. */
    case VISA = 'visa';

    /** Power of attorney from the shareholder. */
    case POWER_OF_ATTORNEY = 'power_of_attorney';

    /** Draft of the acta constitutiva — compiled at ACTA_PREPARATION stage, sent to DocuSign later. */
    case ACTA_DRAFT = 'acta_draft';

    /** Signed acta constitutiva — generated at INCORPORATION stage. */
    case INCORPORATION_ACT = 'incorporation_act';

    /** Constancia de Situación Fiscal (SAT Mexico) — generated at SAT_REGISTRATION stage. */
    case CSF = 'csf';

    /** Bank proof. */
    case BANK_PROOF = 'bank_proof';

    /** RFC registration document from SAT. */
    case RFC_DOCUMENT = 'rfc_document';

    /** e.firma certificate (.cer / .key) — generated at EFIRMA_APPOINTMENT stage. */
    case EFIRMA = 'efirma';

    /** Any other document not covered by the types above. */
    case OTHER = 'other';

    /**
     * Return a human-readable Spanish label for display in the dashboard.
     */
    public function label(): string
    {
        return match ($this) {
            self::KYC_TAX_CERTIFICATE => 'ID Fiscal chino (Tax Certificate)',
            self::KYC_PROOF_OF_ADDRESS => 'Comprobante de domicilio (China)',
            self::KYC_MARRIAGE_CERTIFICATE => 'Acta de matrimonio (China)',
            self::KYC_SPOUSE_PASSPORT => 'Pasaporte del cónyuge',
            self::PASSPORT => 'Pasaporte del accionista',
            self::VISA => 'Visa',
            self::POWER_OF_ATTORNEY => 'Poder notarial',
            self::ACTA_DRAFT => 'Borrador del Acta Constitutiva',
            self::INCORPORATION_ACT => 'Acta constitutiva',
            self::CSF => 'Constancia de Situación Fiscal (SAT)',
            self::BANK_PROOF => 'Comprobante bancario',
            self::RFC_DOCUMENT => 'Documento RFC',
            self::EFIRMA => 'e.firma',
            self::OTHER => 'Otro',
        };
    }

    /**
     * Return true if this document type comes from the China relay (initial KYC package).
     *
     * Useful for filtering which documents arrived from China vs. were generated by Nexum.
     */
    public function isKyc(): bool
    {
        return match ($this) {
            self::KYC_TAX_CERTIFICATE,
            self::KYC_PROOF_OF_ADDRESS,
            self::KYC_MARRIAGE_CERTIFICATE,
            self::KYC_SPOUSE_PASSPORT => true,
            default => false,
        };
    }

    /**
     * Resolve the document type from a relay field name (e.g. "naturalTaxCertificate1").
     *
     * Strips the trailing digit so "naturalTaxCertificate2" resolves the same as "naturalTaxCertificate1".
     *
     * @param  string  $field  Field name from the Singapur relay JSON.
     */
    public static function fromRelayField(string $field): self
    {
        $base = rtrim($field, '0123456789');

        return match ($base) {
            'naturalTaxCertificate' => self::KYC_TAX_CERTIFICATE,
            'naturalProofAddress' => self::KYC_PROOF_OF_ADDRESS,
            'naturalPassport' => self::PASSPORT,
            'naturalMarriageCertificate' => self::KYC_MARRIAGE_CERTIFICATE,
            'naturalSpousePassport' => self::KYC_SPOUSE_PASSPORT,
            default => self::OTHER,
        };
    }
}
