<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * Catalog of trackable events in a denomination's lifecycle.
 *
 * Each event renders on the denomination detail timeline with its own Spanish
 * label, heroicon and color. The enum is the single source of truth so the
 * timeline, filters and any future reporting stay consistent.
 */
enum LegalNameEventTypeEnum: string
{
    /** Denomination record created (generated by AI, manually or from the webhook). */
    case CREATED = 'created';

    /** Pre-submission MUA availability check ran. */
    case AVAILABILITY_CHECKED = 'availability_checked';

    /** Entered the WAIT queue, ready to be submitted. */
    case QUEUED = 'queued';

    /** Submission deferred — outside business hours or no FIEL with capacity. */
    case DEFERRED = 'deferred';

    /** Submission attempt failed (bot error, e.g. HTTP 403). */
    case SUBMISSION_FAILED = 'submission_failed';

    /** Successfully submitted to the MUA bot with a FIEL assigned. */
    case SUBMITTED = 'submitted';

    /** SE took the denomination into review (PENDING → PROCESS). */
    case IN_PROCESS = 'in_process';

    /** SE authorized the denomination. */
    case APPROVED = 'approved';

    /** SE rejected the denomination. */
    case REJECTED = 'rejected';

    /** Authorization constancia PDF received from the bot. */
    case CONSTANCIA_RECEIVED = 'constancia_received';

    /** Pool denomination claimed by a registration. */
    case CLAIMED = 'claimed';

    /**
     * Human-readable Spanish label for the timeline.
     */
    public function label(): string
    {
        return match ($this) {
            self::CREATED => 'Denominación creada',
            self::AVAILABILITY_CHECKED => 'Disponibilidad verificada',
            self::QUEUED => 'En cola de envío',
            self::DEFERRED => 'Envío diferido',
            self::SUBMISSION_FAILED => 'Error al enviar',
            self::SUBMITTED => 'Enviada a la SE',
            self::IN_PROCESS => 'En dictamen',
            self::APPROVED => 'Aprobada por la SE',
            self::REJECTED => 'Rechazada por la SE',
            self::CONSTANCIA_RECEIVED => 'Constancia recibida',
            self::CLAIMED => 'Asignada a expediente',
        };
    }

    /**
     * Heroicon name for the timeline marker.
     */
    public function icon(): string
    {
        return match ($this) {
            self::CREATED => 'heroicon-o-sparkles',
            self::AVAILABILITY_CHECKED => 'heroicon-o-magnifying-glass',
            self::QUEUED => 'heroicon-o-queue-list',
            self::DEFERRED => 'heroicon-o-clock',
            self::SUBMISSION_FAILED => 'heroicon-o-exclamation-triangle',
            self::SUBMITTED => 'heroicon-o-paper-airplane',
            self::IN_PROCESS => 'heroicon-o-arrow-path',
            self::APPROVED => 'heroicon-o-check-badge',
            self::REJECTED => 'heroicon-o-x-circle',
            self::CONSTANCIA_RECEIVED => 'heroicon-o-document-check',
            self::CLAIMED => 'heroicon-o-link',
        };
    }

    /**
     * Filament color token for the timeline marker.
     */
    public function color(): string
    {
        return match ($this) {
            self::CREATED, self::AVAILABILITY_CHECKED => 'gray',
            self::QUEUED, self::IN_PROCESS => 'info',
            self::DEFERRED => 'warning',
            self::SUBMISSION_FAILED, self::REJECTED => 'danger',
            self::SUBMITTED => 'primary',
            self::APPROVED, self::CONSTANCIA_RECEIVED, self::CLAIMED => 'success',
        };
    }
}
